# Generated by Django 5.2.1 on 2025-05-24 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_news_published_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='scheduled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
