# Generated by Django 5.2.1 on 2025-05-24 16:53

from django.db import migrations


def create_initial_data(apps, schema_editor):
    Vertical = apps.get_model('core', 'Vertical')
    Plan = apps.get_model('core', 'Plan')

    # Create verticals
    verticals = [
        Vertical(name='Poder'),
        Vertical(name='Tributos'),
        Vertical(name='Saúde'),
        Vertical(name='Energia'),
        Vertical(name='Trabalhista'),
    ]
    Vertical.objects.bulk_create(verticals)
    # Create plans
    plans = [
        Plan(name='JOTA Info', price=0.00),
        Plan(name='JOTA PRO', price=9.99),
    ]
    Plan.objects.bulk_create(plans)

def reverse_initial_data(apps, schema_editor):
    Vertical = apps.get_model('core', 'Vertical')
    Plan = apps.get_model('core', 'Plan')

    Vertical.objects.all().delete()
    Plan.objects.all().delete()


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_initial_data, reverse_initial_data),
    ]
