# Generated by Django 5.2.1 on 2025-05-24 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20250524_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='is_basic',
            field=models.BooleanField(default=True),
        ),
    ]
