# Generated by Django 5.2.1 on 2025-05-22 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrador'), ('publisher', 'Editor'), ('reader', 'Leitor')], default='reader', max_length=10, verbose_name='Papel'),
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
