# Generated by Django 5.2.1 on 2025-05-24 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_managers_alter_customuser_email'),
        ('core', '0002_auto_20250524_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.plan', verbose_name='Plano'),
        ),
    ]
